import { Box, Button, Flex, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { FiGithub, FiHome } from "react-icons/fi";

const Home: NextPage = () => {
  return (
    <Flex
      height="100vh"
      background="grey.100"
      alignItems="center"
      justifyContent="center"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column" alignItems="center">
        <Box p="2" mb="6">
          <Heading size="3xl">Bulletproof Next</Heading>
        </Box>

        <Text fontSize="md" mb="6">
          Showcasing Best Practices For Building Next.js Applications
        </Text>

        <Flex direction="row">
          <Button leftIcon={<FiHome />} colorScheme="teal">
            Get Started
          </Button>
          <Box width="6" />
          <Button leftIcon={<FiGithub />} colorScheme="teal" variant="outline">
            Github Repo
          </Button>
        </Flex>
      </Flex>
    </Flex>
  );
};

export default Home;
